EXPERIMENT:
  NAME: ""
  TAG: "s2t,amd-recon,clip-base,vit-tiny,layer7,mse,recon-weight-100"
  PROJECT: "clip_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "AMD_RECON"
  TEACHER: "clip_base"
  STUDENT: "vit_tiny"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  SGD:
    MOMENTUM: 0.9
  SCHEDULE: 
    MULTISTEP:
      STAGES: [30, 60, 90]
      RATE: 0.1
  WEIGHT_DECAY: 0.0001
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
AMD:
  M_LAYERS: [7]
  ALIGN_TYPE: 'mse'
  INPUT_SIZE: [224, 224]
  AF:
    ENABLE: True
    CRITERIA:
      THRES: 5.5
    RECON:
      TYPE: 'recon_mha'
  LOSS:
    RECON_WEIGHT: 100.0
    FEAT_WEIGHT: 100.0
